language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
script:
- npm run build
deploy:
  skip_cleanup: true
  provider: npm
  email: ui.e@klarna.com
  api_key:
    secure: AOHfAEV9Rmn7BRilcN7D7fCoavu5Q928oKRcB4jvekmmLyj+MK2uRVPLJoUn1R7MPlSp4tnq4ryALiUliuSrDKNXz2+ypGTDXcP78xCBXZ+/g7DyNRzW0GFT0tj+dPhHVD84F6hN7uV+OFIpyyd38l3GeJeuyWywNvUvBUOTHE5FYsXqW/S0WHxVPULSuXhLmJCbJpFERxkWnp7iIH1eIRIyV6cTe0hDgl6Mvhiaq2CxVsGNXGVS7k6m8e5ywvem/dc6DWNbSTROO5KoYFMXH4N51BOmIi4gCCJScN9RbPcSiAbm9roWvSKv017zRQjGDuM6eMbjSWW3r6leJkVHEJ76Sa20vcXt1BI69kQdwDYTj8Tahji4+ydoTIKYZSwoKO9QLkqnIvhZLAFZmlpuCc/uADAOrviiRkPREAdguF7sbrewg+1W+yX7RFBGm89HyXkQAV0w8LMSr3HlYfWz9tZmEY2XeMVP7sxef43mW6ogxmBrI4m9sdXujoIVxj6ibEMTw2aOafgV8vHqQFltHDtkZogtodHO3cLx1J/jF76IB4YJV9ny31xvg5Zxj93Hgwwjl7u93PD2teKpEl01zfoRKnRlQzw0XHN4OvacRmF5pp7FoWgofvYjIEjiz8dGUx8kN5gx6p18IEd+0yS5vuVI0rYe8v0pV0i3zEiFt4c=
  on:
    tags: true
    repo: klarna/remote-frames
