language: node_js
node_js:
- '8'
script:
- npm run build
deploy:
  skip_cleanup: true
  provider: npm
  email: ui.e@klarna.com
  api_key:
    secure: ZyH35m7nJ9jLC+zoPtZYq1p4MZwuivxjCfa+3ARgP2g5wAkn+gJnQk6pDajolMMPjJ824k7b7r0lCWqLEH6azDwGuWFptkDRA7cZ0dD4oo50B6BRYa4dHnbTMGvLZbmQ7Bo+M5HZo/t/ZKt6w59QX7OBug13UJSej89GbFcR5HAPYDDmVzRX/TZr03TAUxL4ASpdovavGrmaYsrkk4y4JWku2txKVL9XQwchTDF4i1FEMNfZ5PpY8H1/qudIL6z5aPRoC9/fFJGz5gZbMeyyG+Xx882G/yP1uLCLsJvbecXSPT4BwJX79A+ToKNZeyJ2lyEifFci8TE8/l9i1SidvDpn7T37kdE3A1iq5B/dg680G8zOfMZpgaJ2rrhX5UG6y2p8gZkOJn4+fbk31EMzrebeDEYTwGTa5hwLB3ztksGeksziA4u+WTU9xTtxVFIYyZog9/Rfr/vhE0AihnNeT1ah7hr3R7KrIox5f4RmasqE5ocIhYxhrEppPirFVsNuu0urDUJi88i49P45BW6hTGPqMNQM3FCFXj9POBl+LlMy4LeoDJAxmqhq0SkioG09VVamhLEkzOVyvW1AR7Tyj1RXzISePriSx2u5mF+j3EsCY5SjIsRBkyaGrbEMi3AtwtU0McCmesgB0s57KLOHDvxiKwyV0HkYpu2d1EnPPkA=
  on:
    tags: true
    repo: klarna/remote-frames
